- name: Run Deploy Script
  shell: powershell
  env:
    DB_SERVER: ${{ secrets.DB_SERVER }}
    DB_USER: ${{ secrets.DB_USER }}
    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  run: |
    Write-Host "SERVER=$env:DB_SERVER"
    Write-Host "USER=$env:DB_USER"

    cd $env:GITHUB_WORKSPACE

    Write-Host "Current Directory:"
    dir

    Write-Host "Scripts Folder:"
    dir .\scripts

    .\scripts\Deploy.ps1