name: SQL CI/CD Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show files
        shell: powershell
        run: |
          dir
          dir .\scripts

      - name: Run Deploy Script
        shell: powershell
        env:
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          Write-Host "SERVER=$env:DB_SERVER"
          Write-Host "USER=$env:DB_USER"

          cd $env:GITHUB_WORKSPACE
          .\scripts\Deploy.ps1
